version: '3'
services:
  app:
    container_name: "app"
    build: "./docker/go-develop"
    volumes:
      - ".:${GO_PROJECT_DIR}"
    ports:
      - "8080:8080"
    environment:
      GO_WORK_DIR: "${GO_PROJECT_DIR}/app"